name: 反馈bug
description: 提出一个bug报告.
labels: ['bug']
body:
  - type: checkboxes
    id: check
    attributes:
      label: 是否已经存在相同issue?
      description: 请搜索Issues查看是否已经存在描述了你要提出的bug的issue.
      options:
      - label: 我已经搜索了Issues
        required: true
  - type: textarea
    id: version
    attributes:
      label: 版本号
      description: 输入你所使用的Maa-HBR版本号
    validations:
      required: true
  - type: textarea
    id: describe
    attributes:
      label: 问题表现
      description: 简要描述你的问题
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: 如何复现
      description: 重现该行为的步骤
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: 预期行为
      description: 简要描述你期望发生的事情
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: 相关 logs
      description: 请上传bug发生后的debug/maa.log或maa.bak.log文件。
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: 截图
      description: |
        如果有，添加屏幕截图以帮助解释你的问题。
        提示: 可以通过点击这个区域，然后把文件拖进来添加图片或日志文件。
    validations:
      required: false