name: 其他问题
description: 任何其他问题
labels: []
body:
  - type: checkboxes
    id: check
    attributes:
      label: 是否已经存在相同issue?
      description: 请搜索Issues查看是否已经存在描述了你要提出的bug的issue.
      options:
      - label: 我已经搜索了Issues
        required: true
  - type: textarea
    id: describe
    attributes:
      label: 具体内容
      description: 简要描述你的问题
    validations:
      required: true
