name: mirrorchyan

on:
  workflow_dispatch:

jobs:
  mirrorchyan:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        os: [win]
        arch: [x86_64]
    steps:
      - id: uploading
        uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: "Maa-HBR-${{ matrix.os }}-${{ matrix.arch }}-*.zip"
          mirrorchyan_rid: Maa-HBR

          owner: KarylDAZE
          repo: Maa-HBR
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}

  mirrorchyan_res:
    runs-on: macos-latest
    steps:
      - id: uploading
        uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: "Maa-HBR-win-x86_64-*.zip"
          pick_files: '["resource", "interface.json"]'
          exclude_files: '["resource/base/model/ocr/**"]'
          mirrorchyan_rid: Maa-HBR

          owner: KarylDAZE
          repo: Maa-HBR
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
